Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Run actions/deploy-pages@v4
(node:2159) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Fetching artifact metadata for "github-pages" in this workflow run
Found 1 artifact(s)
Creating Pages deployment with payload:
{
	"artifact_id": 7960364223,
	"pages_build_version": "76882a0d21783be37c5d873ce5da92916ad748cd",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Missing environment. Ensure your workflow's deployment job has an environment. Example:
jobs:
  deploy:
    environment:
      name: github-pages

    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:125:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:74:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version 76882a0d21783be37c5d873ce5da92916ad748cd. Request ID 9040:2EA7E3:DB78F8:DE8033:6A42B3B4 Responded with: Missing environment. Ensure your workflow's deployment job has an environment. Example:
jobs:
  deploy:
    environment:
      name: github-pages
